title: Eugene Piven
url: http://epiven.pro
email: epiven@gmail.com
description: Infrastructure Developer
timezone: Europe/Moscow
permalink: pretty
theme: jekyll-theme-slate
exclude: ['Gemfile.lock', 'Gemfile', '.bundle/', 'CNAME']
plugins:
  - jekyll-feed
